name: Robot SEACE

on:
  schedule:
    - cron: '0 13 * * *' # 8:00 AM Perú
  workflow_dispatch:

jobs:
  run-robot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Actualizado para evitar errores de librerías nuevas

      - name: Instalar Librerías
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests pdfplumber google-generativeai

      - name: Ejecutar Scraper
        env:
          GOOGLE_WEBHOOK: ${{ secrets.GOOGLE_WEBHOOK }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python scraper.py
